### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by luisadha** [wibi9424/ascii-video#1]
Hello sir, how to use this tool?

**Comment by wibi9424** [comment]
> Hello sir, how to use this tool?

- click text at the top, that is an options.
- src for picking video file from your device
- camera for displaying camera as ascii

try another option like turn color1 to true by click on the text

dont forget after chose file, click 'paused' text or ascii text full M in the bottom to start playing.

**Comment by wibi9424** [comment]
please open Discussions tab for questions!
